# Generated by Django 4.1.3 on 2022-12-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('date', models.DateField()),
                ('min_duration', models.TimeField()),
                ('max_duration', models.TimeField()),
                ('machine_number', models.IntegerField()),
                ('time_from', models.TimeField()),
                ('time_before', models.TimeField()),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
